# Generated by Django 4.2.7 on 2023-11-15 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('set_is_active', 'can block users (is active)')]},
        ),
    ]
