# Generated by Django 4.2.7 on 2023-11-10 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_time', models.TimeField(verbose_name='время рассылки')),
                ('periodicity', models.CharField(max_length=300, verbose_name='периодичность')),
                ('mailing_status', models.CharField(max_length=50, verbose_name='статус рассылки')),
                ('letter_subject', models.CharField(max_length=100, verbose_name='тема письма')),
                ('letter_body', models.CharField(max_length=500, verbose_name='тело письма')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
        migrations.CreateModel(
            name='NewsletterLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, null=True, verbose_name='дата и время последней попытки')),
                ('status', models.BooleanField(blank=True, default=False, null=True, verbose_name='статус попытки')),
                ('mail_server_response', models.CharField(max_length=100, verbose_name='ответ почтового сервиса')),
                ('newsletter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsletters.newsletter')),
            ],
            options={
                'verbose_name': 'логи',
                'verbose_name_plural': 'логи',
            },
        ),
    ]
