# Generated by Django 4.2.7 on 2023-11-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField()),
                ('fio', models.CharField(max_length=250)),
                ('comment', models.TextField(blank=True, null=True)),
                ('owner', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='newsletter',
            name='next_run',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='mailing_status',
            field=models.CharField(choices=[('new', 'создана'), ('work', 'запущена'), ('stop', 'завершена')], default='new', max_length=50, verbose_name='статус рассылки'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='periodicity',
            field=models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно')], max_length=300, verbose_name='периодичность'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='clients',
            field=models.ManyToManyField(to='newsletters.client'),
        ),
    ]
