# Generated by Django 4.2.7 on 2023-11-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0003_client_newsletter_next_run_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='mailing_time',
            field=models.TimeField(blank=True, null=True, verbose_name='время рассылки'),
        ),
    ]
