# Generated by Django 4.2.7 on 2023-11-14 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0004_alter_newsletter_mailing_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'permissions': [('change_mailing_status', 'can change status of newsletters')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
