# Generated by Django 4.2.7 on 2023-11-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0005_alter_newsletter_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='letter_body',
            field=models.TextField(verbose_name='тело письма'),
        ),
    ]
