# Generated by Django 4.2.7 on 2023-11-15 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0008_rename_owner_client_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='author',
        ),
    ]
