# Generated by Django 4.2.7 on 2023-11-15 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0010_client_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'permissions': [('set_mailing_status', 'can change status of newsletters')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
